# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61859aaa93d007dd25bfc0f08150ef09940e726fc9989f0f57875f79d1f0e53d8b66c9be236ee27d2fcac9aa9033692d5b4273fa984e56b686592bc9671c53f1

test:
  secret_key_base: ecc58f6b3001b4961b9f4d6cef7435d2aa2163592ebf65e61a49a96c0e818e717fc68cdabc22dd0057a601cced88c1ac6ccc3921b0ad91a8553120cb23747374

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
